### register
GET http://127.0.0.1:5001/list
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjQ5NDQ4MGY0LTU2ZjMtNDYxZC05ZWE2LTFjZjA2MWVlMzM1ZCIsImV4cCI6MTY1MzMyMzYwM30._6nRJup7ONzYAAmlcGtXkidrdd1LEFha_nvNCz4Ckm4