### register
GET http://127.0.0.1:5001/list
Content-Type: application/json
Authorization: Token eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6ImM2N2E0N2I2LTliOTEtNDQ0NC1iNjk4LWYxZDdkZDRlOGIyMyIsImV4cCI6MTY1MzMwNDk3M30.BjzgwrcOzK5Axkk0Ww4hh_xAY9GE9wehp6pY5Nl4W8k